name: XiaoJoin
main: zbv5.cn.XiaoJoin.Main
version: 1.0.0
api: 1.0.0
author: 逍遥
softdepend:
  - PlaceholderAPI
commands:
  XiaoJoin:
    description: 重载
    aliases: ["xj", "xjoin"]
permissions:
  XiaoJoin.formats.default:
    description: 默认形式权限
    default: true
  XiaoJoin.commands.reload:
    description: 重载配置
    default: op
