############################################################################################################################
#                       XiaoJoin
#
#   执行格式支持:
#    [message] 向玩家发出一句话       例子:   - "[message]&8好哥哥,你真棒~"
#    [bc] 向服务器发出公告            例子:   - "[bc]&8服主你太帅了~"
#    [console] 服务器发送指令         例子:   - "[console]say 233"
#    [player] 玩家发送指令            例子:   - "[player]help"
#    [op] 玩家以OP身份发送指令        例子:   - "[op]give {player} 1 1"
#    [playerchat] 玩家发送聊天消息    例子:   - "[playerchat]我要充648!"
#    [title] 给玩家发送Title          例子1:   - "[title]欢迎"
#                                     例子2:   - "[title]欢迎,{player}"
#                                     例子3:   - "[title]欢迎,{player},1,50,15"       后三int数字分别为fadeIn stay fadeOut
#    [ActionBar] 给玩家发送ActionBar  例子1:   - "[ActionBar]欢迎"
#                                     例子2:   - "[ActionBar]欢迎,1,50,15"       后三int数字分别为fadeIn stay fadeOut
#
#   本插件已支持 PlaceholderAPI变量    其他额外变量和需求欢迎评论留言
############################################################################################################################

#取消原版自带的玩家进入消息
CancelJoinMessage: true

#延迟执行进入消息
#因为在测试过程中发现玩家进入服务器后在加载页面就会触发事件,所以为了title等操作正常运行添加延迟执行Join操作
#模拟器以及古董安卓机测试大概在10-15s左右即可 请根据实际情况进行调整
Delay:
  #是否启用
  Enable: false
  #延迟时长(s)
  DelayTime: 15

#格式列表
Formats:
  #默认组
  default:
    #优先级 越小越优先
    priority: 20200202
    #玩家进入服务器触发
    join:
      - "[bc]&8[&a+&8]{player}"
    #玩家退出服务器触发
    quit:
      - "[bc]&8[&c-&8]{player}"
  #VIP组 需要给玩家权限XiaoJoin.formats.vip   依次类推 增加一个格式就要给要设置的玩家或权限组权限,并且调整优先级
  vip:
    #需小于默认组
    priority: 2020
    join:
      - "[bc]&e========================="
      - "[bc]&8[&a+&8]&b尊贵的会员玩家&a{player}&b进入了服务器."
      - "[bc]&e========================="
    quit:
      - "[bc]&8[&c-&8]&b尊贵的会员玩家&a{player}&b离开了服务器."